title: While Gaming
baseurl: /
permalink: '/:title/'
layout_style: overflow
palette: blue
header:
  title: While ( Gaming )
  tagline: My Adventures in Gaming
  profile_img: images/avatar.png
  bg: dark
  has_nav: true
  has_social: true
footer:
  content: ''
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ssg-build.sh
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
collections:
  posts:
    permalink: 'posts/:title'
  games:
    permalink: 'games/:title'
pagination:
  enabled: true
  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false
  collection: 'posts'
  per_page: 10
  permalink: '/page/:num/' 
  limit: 0
  extension: html
  indexpage: 'index'
