title: While Blogging
baseurl: /
url: https://www.whileblogging.com
permalink: '/:title/'
layout_style: overflow
palette: blue
header:
  title: While ( Blogging )
  tagline: My Adventures in Gaming, Reading, Coding and Life
  profile_img: images/avatar.png
  bg: dark
  has_nav: true
  has_social: true
menu:
  - title: home
    url: index.html
  - title: While Blogging
    url: blog.html
  - title: While Gaming
    url: gaming/index.html
  - title: While Reading
    url: reading/index.html
  - title: While Coding
    url: coding/index.html
  - title: contact
    url: contact.html
    
footer:
  content: ''
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ssg-build.sh
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
collections:
  posts:
    permalink: 'posts/:title'
  games:
    permalink: 'games/:title'  
  gaming:
    permalink: 'gaming/:title'
  reading:
    permalink: 'reading/:title'
  coding:
    permalink: 'coding/:title'
pagination:
  enabled: true
  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false
  collection: 'posts'
  per_page: 5
  permalink: '/page/:num/' 
  limit: 0
  extension: html
  indexpage: 'index'
